### PR TITLE
Fix multiple bugs

### LINKED ISSUE #10: Transaction -> IsIncome/IsExpence not working
Transactions are not differentiated (e.g. deposit interest and spendings only differ in sign)

### PR DESCRIPTION
**Pull request by siriak**
Fixes TimeSeries returning incorrect smoothed value
Fixes Transactions deserialization not working correctly (closes #10)
Fixes trends chart not redrawing when data updated
Updates trends chart color palette to be more contrast

### CODE REVIEW

File: WinFormsUI/MainForm.cs [hunk 1]
```diff
@@ -9,12 +9,9 @@ namespace WinFormsUI
     public partial class MainForm : Form
     {
         Date startDate, endDate;
-        event Action OnFilteringUpdated;
+        event Action OnFilteringUpdated = () => { };
```
Comment (Adelhaide22) [inline WinFormsUI/MainForm.cs]: Why we need this?

Comment (siriak) [reply WinFormsUI/MainForm.cs]: To ensure that OnFilteringUpdated is never null and don't check for that before invoking it.
